export const entitiesData = [
    {
        id: 1,
        img: 0,
        title: 'ABC Generic company',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 2,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 3,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 4,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 5,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 6,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 7,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 8,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 9,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 10,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 11,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 12,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 13,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 14,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 15,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 16,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },

    {
        id: 17,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 18,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 19,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 20,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 21,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 22,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 23,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 24,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 25,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 26,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 27,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 27,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 29,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 30,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 31,
        img: 4,
        title: 'World company SAS',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
    {
        id: 32,
        img: 6,
        title: 'Subsid Corp Ltd',
        description: 'Caracas 1050, Distrito Capital, Venezuela',
    },
];


export const filterData = [
    {
        id: 2,
        field1: "Where",
        field2: "Status",
        field3: "Is",
        field4: "In",
        icon: "./media/icons/arrow-down.svg",
    },
    {
        id: 3,
        field1: "And",
        field2: "Status",
        field3: "Ends before",
        field4: "In",
        icon: "./media/icons/arrow-down.svg",
    },
];
